support query string
attwad/nessie pull request #13
Opened 2021-01-15 17:58 UTC by qudongfang

2021-01-17 14:01 UTC, attwad requested changes
Looks reasonable, could you add a test to cover this new behavior in nessie_test.go please?

2021-01-18 11:53 UTC, qudongfang commented
> Looks reasonable, could you add a test to cover this new behavior in nessie_test.go please?

Thanks for your response(especially it was during the weekend!).

I'd like to note that: I introduced a dependency to help with decoding a `struct` from `http.Form`,  it seems to be the first one. 
even though the changes to the tests themself are pretty minor.

2021-01-18 12:06 UTC, attwad commented on go.mod
> +go 1.15
Can you change the github actions workflow to build using go 1.15 as well please?
https://github.com/attwad/nessie/blob/master/.github/workflows/go.yml#L10

2021-01-18 12:17 UTC, attwad approved these changes

2021-01-18 12:18 UTC, merged